name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  scripts:
    runs-on: windows-latest
    steps:
      - name: Run in default shell
        run: echo "This step runs in the default shell"

      - name: Run in bash
        run: echo "This step runs in bash"
        shell: bash

      - name: Run in PowerShell Core
        run: Write-Host "This step runs in PowerShell Core"
        shell: pwsh

      - name: Run in PowerShell
        run: Write-Host "This step runs in PowerShell"
        shell: powershell

  run_command:
    runs-on: windows-latest
    steps:
      - name: Run in PowerShell on Windows by default
        run: echo "This step runs in PowerShell on Windows by default"

      - name: Run in CMD on Windows explicitly
        run: echo "This step runs in CMD on Windows explicitly"
        shell: cmd

  conditional:
    runs-on: ubuntu-latest
    steps:
      - name: Run based on condition
        run: echo "This step runs with str equals 'ABC' and num equals 123"
        if: ${{ env.str == 'ABC' && env.num == 123 }}

  sequence:
    runs-on: ubuntu-latest
    jobs:
      - name: Initial Job
        runs-on: ubuntu-latest
        steps:
          - name: Initial Step
            run: echo "This job will be run first."

      - name: Fanout Job 1
        runs-on: ubuntu-latest
        needs: Initial Job
        steps:
          - name: Fanout Step 1
            run: echo "This job will run after the initial job, in parallel with fanout2."

      - name: Fanout Job 2
        runs-on: ubuntu-latest
        needs: Initial Job
        steps:
          - name: Fanout Step 2
            run: echo "This job will run after the initial job, in parallel with fanout1."

      - name: Fanin Job
        runs-on: ubuntu-latest
        needs: [Fanout Job 1, Fanout Job 2]
        steps:
          - name: Fanin Step
            run: echo "This job will run after fanout1 and fanout2 have finished."

  run_python:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Run Python script
        run: python script.py
